# Generated by Django 4.1.3 on 2022-11-16 11:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_product_available_size_product_color_product_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AlterField(
            model_name='product',
            name='available_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '38'), (2, '39'), (3, '40'), (4, '41'), (5, '42'), (6, '43'), (7, '44'), (8, '45')], max_length=49),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('1', 'white'), ('2', 'black'), ('3', 'grey'), ('4', 'brown'), ('5', 'red'), ('6', 'blue'), ('7', 'green'), ('8', 'multicolor'), ('9', 'other colors')], max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'women’s shoes'), (2, 'men’s shoes'), (3, 'unisex shoes'), (4, 'kids’ shoes'), (5, 'lifestyle'), (6, 'sneakers'), (7, 'winter shoes'), (8, 'dress shoes'), (9, 'flip-flops'), (10, 'sandals'), (11, 'running'), (12, 'shoes for other sports'), (13, 'other shoes')], max_length=49),
        ),
    ]
