# Generated by Django 4.1.3 on 2022-11-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('toppings', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=999)),
                ('sale', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('votes', models.PositiveIntegerField()),
            ],
        ),
    ]
