# Generated by Django 4.1.3 on 2022-11-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.IntegerField(unique=True),
        ),
    ]
