# Generated by Django 4.1.4 on 2022-12-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0003_order_rename_owner_shoppingcart_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_app.shoppingcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_app.product')),
            ],
        ),
    ]
