# Generated by Django 4.1.3 on 2022-11-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0003_remove_product_toppings_remove_product_votes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=5),
        ),
    ]
