# Generated by Django 4.1.4 on 2022-12-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0004_shoppingcartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
