# Generated by Django 4.1.3 on 2022-11-16 09:13

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0005_alter_comment_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '38'), (2, '39'), (3, '40'), (4, '41'), (5, '42'), (6, '43'), (7, '44'), (8, '45')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.IntegerField(choices=[(1, 'white'), (2, 'black'), (3, 'grey'), (4, 'brown'), (5, 'red'), (6, 'blue'), (7, 'green'), (8, 'multicolor'), (9, 'other colors')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.IntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'unisex')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Running'), ('2', 'Lifestyle'), ('3', 'heels'), ('4', 'winter shoes'), ('4', 'winter'), ('4', 'winter'), ('4', 'wier'), ('4', 'winter'), ('5', 'other shoes')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=999)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_app.product')),
            ],
        ),
    ]
