# Generated by Django 4.1.4 on 2022-12-10 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0006_remove_shoppingcart_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop_app.customer'),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop_app.customer'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop_app.customer'),
        ),
    ]
