# Generated by Django 4.1.4 on 2022-12-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0007_alter_order_customer_alter_shippingadress_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop_app.shoppingcart'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
